/**
 * What `shared-agent-framework/decisions` creates in a database: the `decisions` table, and the
 * PostgreSQL schema it lives in. Keep it to the table and the values that define it, and add no
 * import of another component's schema: this log references nobody, so this subpath can be listed
 * on its own.
 *
 * A Decision is immutable. No column is ever updated, and nothing removes a row: no delete, no TTL,
 * no sweeper and no supersession field. A reversal is a new Decision whose statement says so.
 */

import { integer, pgSchema, text, timestamp } from "drizzle-orm/pg-core";

/**
 * The PostgreSQL schema every table below lives in, `saf_decisions`.
 *
 * Prefixed because the framework is installed into a database it does not own, and not
 * configurable: the table is compiled against this object, and the same object is what a
 * generation reads.
 */
export const decisionsSchema = pgSchema("saf_decisions");

/**
 * One Decision: a Signed Statement, numbered and kept.
 *
 * Four columns, and no `user_id`. The log is global and a Decision is addressed to nobody, which is
 * the whole of why a commitment here is a commitment.
 */
export const decisions = decisionsSchema.table("decisions", {
  /**
   * The number, global and from 1, and the primary key. There is no `id` beside it, because a
   * global sequence is already unique.
   *
   * `GENERATED BY DEFAULT AS IDENTITY` and not `ALWAYS`, because supplying the value by hand is
   * what this Component does. The JWS binds `seq`, so `decisions.ts` draws it with `nextval` before
   * signing. `ALWAYS` would refuse that.
   *
   * A gap in it is expected and means nothing: a rolled-back transaction burns a number. Nothing
   * compacts, checks or reports one.
   */
  seq: integer("seq").primaryKey().generatedByDefaultAsIdentity(),
  /**
   * The whole content, a plain string. No `jsonb` and no payload convention, because a fixed shape
   * is what makes one verifier serve every deployment.
   *
   * No length bound here or on the route. The server's own `bodyLimit` is the bound, and it is the
   * Operator's to raise.
   */
  statement: text("statement").notNull(),
  /**
   * The compact JWS over `{ seq, createdAt, statement }`, base64url, and not null.
   *
   * That `NOT NULL` is why the write path draws its number before signing. Inserting, signing and
   * updating would make this column nullable in every record type forever. And PostgreSQL cannot
   * enforce that it gets filled: `DEFERRABLE` does not apply to `NOT NULL`.
   *
   * `text` holding base64url and not `bytea`. It crosses the API in that form anyway. Storing the
   * encoded form keeps the stored bytes and the served bytes from disagreeing. Named `jws` because
   * it holds a whole JWS, of which the signature is one of three segments.
   */
  jws: text("jws").notNull(),
  /**
   * When it was published, generated in JS and with no database default at all.
   *
   * Do not "fix" this to `clock_timestamp()` to match `messages.created_at`. The signed timestamp
   * and the stored timestamp have to be the same value. One value reaching both is the only
   * guarantee.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const decisionsTables = { decisions };
