-- Generated by `npm run migrations:generate -- --config drizzle.users.config.ts`,
-- then edited in one respect: `drizzle-kit` wrote `CREATE SCHEMA "saf_users";` as
-- the first statement and it has been removed. `store.migrate` creates the
-- descriptor's schema itself, because the tracking table lives in it, so the
-- generated line always arrives at a schema that already exists and fails the very
-- first migration. Every migration folder we ship has this line removed, and
-- `src/core/migrations.test.ts` fails if one is left in.
CREATE TABLE "saf_users"."users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"attributes" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"password_hash" text,
	"created_at" timestamp with time zone DEFAULT clock_timestamp() NOT NULL
);
