-- Generated by `npm run migrations:generate -- --config drizzle.users.config.ts`,
-- then renamed: `drizzle-kit` names a migration after two random words, and the
-- `tag` in `meta/_journal.json` was renamed with it: the journal is what names the
-- file to read, so the two must agree. No `CREATE SCHEMA` line to remove here: only
-- a first migration carries one, and 0000 already created this schema.
CREATE TABLE "saf_users"."tokens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"token_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "tokens_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
ALTER TABLE "saf_users"."tokens" ADD CONSTRAINT "tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "saf_users"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tokens_user_idx" ON "saf_users"."tokens" USING btree ("user_id");