import type { MigrationDescriptor } from "../db/index.ts";
import { httpMessagesSchema } from "./schema.ts";

/**
 * The HTTP Messenger's migration descriptor: inert data registered with the Db, which
 * applies it alongside the other parts' when `db.migrate()` is called and verifies it at
 * `db.start()` (ADR-0022, ADR-0032).
 *
 * Its own schema and its own tracking table, mandatory rather than tidy for the reason the
 * User Directory's are: Drizzle's guard compares folder timestamps against only the newest
 * row of a tracker, so two parts sharing one would have the older part's migrations
 * silently skipped while `migrate` resolved successfully.
 *
 * **Registration order is load-bearing here and nowhere else.** `db.migrate()` applies
 * descriptors in registration order, which is construction order, and this folder's first
 * migration references `saf_users.users` — so the User Directory must be constructed
 * before the HTTP Messenger (ADR-0036). Nothing checks it. The failure is PostgreSQL's
 * `schema "saf_users" does not exist` — or `relation "saf_users.users" does not exist` where
 * the schema is there and the table is not — which names the missing thing plainly enough to
 * leave alone, and `migrations.test.ts` pins that it stays legible.
 *
 * The relative `../../migrations/http-messages` is what makes `dist` mirroring `src`
 * load-bearing — the same relative path has to reach the same folder from
 * `src/http-messenger/migrations.ts` and from `dist/http-messenger/migrations.js`. It is a
 * `URL` and not a path so that resolution is against this module rather than the working
 * directory: the folder ships inside the package, and a `process.cwd()` relative path
 * passes every test in this repository and breaks for every Operator.
 *
 * The SQL is generated by `npm run migrations:generate -- --config
 * drizzle.http-messages.config.ts` and committed, then hand-edited twice — the generated
 * `CREATE SCHEMA` out, the foreign key in. Operators never run a schema generation tool.
 */
export const httpMessagesMigrations: MigrationDescriptor = {
  folder: new URL("../../migrations/http-messages", import.meta.url),
  // Taken from the schema object rather than spelled again: the table is compiled
  // against that name, so a descriptor naming another would migrate one place and read
  // another, and every query would fail on a missing relation.
  schema: httpMessagesSchema.schemaName,
  table: "__migrations",
};
