-- Generated by `npm run migrations:generate`, then edited in one respect:
-- `drizzle-kit` wrote `CREATE SCHEMA "saf_signals";` as the first statement and it
-- has been removed. `db.migrate` creates the descriptor's schema itself,
-- because the tracking table lives in it, so the generated line always arrives at
-- a schema that already exists and fails the very first migration. Every
-- migration folder we ship has this line removed, and `migrations.test.ts` fails
-- if one is left in.
CREATE TABLE "saf_signals"."runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"signal_id" uuid NOT NULL,
	"session" text,
	"prompt" text NOT NULL,
	"state" text DEFAULT 'pending' NOT NULL,
	"error" text,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	CONSTRAINT "runs_state_known" CHECK ("saf_signals"."runs"."state" in ('pending', 'running', 'done', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "saf_signals"."signals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" text NOT NULL,
	"payload" jsonb NOT NULL,
	"emitted_at" timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
	"state" text DEFAULT 'pending' NOT NULL,
	"error" text,
	CONSTRAINT "signals_state_known" CHECK ("saf_signals"."signals"."state" in ('pending', 'processing', 'done', 'failed'))
);
--> statement-breakpoint
ALTER TABLE "saf_signals"."runs" ADD CONSTRAINT "runs_signal_id_signals_id_fk" FOREIGN KEY ("signal_id") REFERENCES "saf_signals"."signals"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "runs_signal_idx" ON "saf_signals"."runs" USING btree ("signal_id");--> statement-breakpoint
CREATE INDEX "signals_pending_idx" ON "saf_signals"."signals" USING btree ("state","emitted_at");