import type { MigrationDescriptor } from "../db/index.ts";
import { decisionsSchema } from "./schema.ts";

/**
 * Decisions' migration descriptor: inert data registered with the Db, which applies it
 * alongside the other parts' when `db.migrate()` is called and verifies it at `db.start()`
 * (ADR-0022, ADR-0032).
 *
 * Its own schema and its own tracking table, mandatory rather than tidy for the reason every
 * other part's are: Drizzle's guard compares folder timestamps against only the newest row of
 * a tracker, so two parts sharing one would have the older part's migrations silently skipped
 * while `migrate` resolved successfully.
 *
 * **Registration order is not load-bearing here**, which is the difference from the HTTP
 * Messenger and is worth stating because a reader arriving from that part will look for the
 * constraint. This table references nothing outside its own schema, so it applies wherever it
 * lands in the order and imposes no construction-order dependency on the User Manager
 * ([ADR-0043](../../docs/adr/0043-decisions-are-one-global-log.md)).
 *
 * The relative `../../migrations/decisions` is what makes `dist` mirroring `src`
 * load-bearing — the same relative path has to reach the same folder from
 * `src/decisions/migrations.ts` and from `dist/decisions/migrations.js`. It is a `URL` and not
 * a path so that resolution is against this module rather than the working directory: the
 * folder ships inside the package, and a `process.cwd()` relative path passes every test in
 * this repository and breaks for every Operator.
 *
 * The SQL is generated by `npm run migrations:generate -- --config drizzle.decisions.config.ts`
 * and committed, then hand-edited once, to take the generated `CREATE SCHEMA` out. Operators
 * never run a schema generation tool.
 */
export const decisionsMigrations: MigrationDescriptor = {
  folder: new URL("../../migrations/decisions", import.meta.url),
  // Taken from the schema object rather than spelled again: the table is compiled against that
  // name, so a descriptor naming another would migrate one place and read another, and every
  // query would fail on a missing relation.
  schema: decisionsSchema.schemaName,
  table: "__migrations",
};
