/**
 * Decisions' one table, in the part's own PostgreSQL schema
 * ([`data-model.md`](../../docs/data-model.md)).
 *
 * **Public API, re-exported from `shared-agent-framework/decisions`**, for the reason the other
 * components' schemas are: an Operator barrels that subpath into their own `schema.ts` and
 * generates from it ([ADR-0046](../../docs/adr/0046-the-operator-owns-migrations.md),
 * [ADR-0047](../../docs/adr/0047-a-component-is-one-subpath.md)). That reverses ADR-0021/0022's
 * "deliberately absent from the `/decisions` subpath": `decisionsSchema` and `decisions` are on
 * it now, beside `createDecisions`. No part reading another's tables remains a discipline rather
 * than something the objects being private enforces.
 *
 * An Operator's `drizzle-kit` reads this file, through their barrel, so keep it to the table
 * and the values it is defined in terms of. Unlike the HTTP Messenger's it imports no other
 * part's schema: this log references nobody, so a barrel carrying it alone generates cleanly
 * ([ADR-0043](../../docs/adr/0043-decisions-are-one-global-log.md)).
 *
 * A Decision is **immutable** — no column is ever updated, literally and not "not after
 * publishing" — and nothing removes one: no delete, no TTL, no sweeper and no supersession
 * field, so the table grows forever exactly as `messages` and `tokens` do. A reversal is a new
 * Decision whose statement says so.
 */

import { integer, pgSchema, text, timestamp } from "drizzle-orm/pg-core";

/**
 * Decisions' schema, named for its subject rather than for the part, and prefixed for the
 * reason the other three are: the framework is installed into a database it does not own, and
 * this name is not an Operator's to change — the table below is compiled against it, and an
 * Operator's generation reads that same object, so renaming it is a migration in somebody
 * else's database.
 */
export const decisionsSchema = pgSchema("saf_decisions");

/**
 * One Decision: a Signed Statement, numbered and kept.
 *
 * Four columns, and the seven that were considered are recorded in the data model. **No
 * `user_id`** above all: the log is global and a Decision is addressed to nobody, which is the
 * framework's first deliberately shared surface and the whole of why a commitment here is a
 * commitment at all (ADR-0043).
 */
export const decisions = decisionsSchema.table("decisions", {
  /**
   * The number, global and from 1, and the primary key — so there is no `id` beside it: a
   * global sequence is already unique, so a uuid would be neither a better cursor nor a better
   * handle and would save no query.
   *
   * `GENERATED BY DEFAULT AS IDENTITY` and **not `ALWAYS`**, precisely because supplying the
   * value by hand is what this part does: the JWS binds `seq`, so `decisions.ts` draws it with
   * `nextval` before signing and hands it to the insert. `ALWAYS` would refuse that.
   *
   * A gap in it is expected and meaningless — a rolled-back transaction burns a number — and
   * gaplessness would prove nothing anyway, since the Operator is trusted and owns the
   * database. Nothing compacts, checks or reports one.
   */
  seq: integer("seq").primaryKey().generatedByDefaultAsIdentity(),
  /**
   * The whole content, a plain string. No `jsonb` and no payload convention: fixing the shape
   * is what makes one verifier serve every deployment, the same move `messages.text` makes.
   *
   * No length bound here or on the route: the server's own `bodyLimit` is already the bound and
   * it is the Operator's to raise on the server they constructed.
   */
  statement: text("statement").notNull(),
  /**
   * The compact JWS over `{ seq, createdAt, statement }`, base64url, and **not null**.
   *
   * That `NOT NULL` is the reason the write path draws its number before signing rather than
   * inserting, signing and updating. The alternative is correct inside one transaction and was
   * rejected for a cost that is permanent where the state it models lasts microseconds: this
   * column would be nullable in the schema and therefore optional in the record type at every
   * surface forever, and **PostgreSQL cannot enforce that it gets filled** — `DEFERRABLE`
   * applies to `UNIQUE`, `PRIMARY KEY`, `EXCLUDE` and `REFERENCES`, not to `NOT NULL`
   * (ADR-0043).
   *
   * `text` holding base64url and not `bytea`: it crosses the API in that form regardless, and
   * storing the encoded form is what keeps the stored bytes and the served bytes from
   * disagreeing. Named `jws` and not `signature` because it holds a whole JWS, of which the
   * signature is one of three segments.
   */
  jws: text("jws").notNull(),
  /**
   * When it was published, generated **in JS** and with no database default at all.
   *
   * This is the one column a reader will otherwise "fix" to match `messages.created_at`, which
   * defaults to `clock_timestamp()`. It must not: the signed timestamp and the stored
   * timestamp have to be the same value, and the only way to guarantee that is for one value
   * to reach both. `messages`' own reason for `clock_timestamp()` is satisfied for free here,
   * each publish calling `new Date()` itself.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

/**
 * Everything Decisions keeps, as `db.handle` wants it: one object, so every module of this
 * part asks for the same handle by the same name.
 */
export const decisionsTables = { decisions };
