FROM golang:1.25-alpine

RUN apk add --no-cache bash

RUN go install github.com/fiatjaf/nak@latest

COPY send.sh /usr/local/bin/send.sh
RUN chmod +x /usr/local/bin/send.sh

ENTRYPOINT ["/usr/local/bin/send.sh"]
