-- Generated by `npm run migrations:generate -- --config drizzle.http-messages.config.ts`,
-- then renamed and edited in two respects.
--
-- Renamed because `drizzle-kit` names a migration after two random words, and the `tag` in
-- `meta/_journal.json` was renamed with it: the journal is what names the file to read, so
-- the two must agree.
--
-- Edited, first, to remove the `CREATE SCHEMA "saf_http_messages";` the generator wrote as
-- its first statement. `db.migrate` creates the descriptor's schema itself, because the
-- tracking table lives in it, so the generated line always arrives at a schema that already
-- exists and fails the very first migration of a new deployment. Every shipped folder has
-- this line removed, and `src/signals/migrations.test.ts` fails if one is left in.
--
-- Edited, second, to **add** the foreign key below, which `drizzle-kit` cannot generate:
-- `src/http-messenger/schema.ts` may not import `../users/schema.ts`, or the generator would
-- emit `CREATE TABLE saf_users.users` into this folder (ADR-0036). Unlike the removal above,
-- a forgotten addition is silent — every test would pass against a database that does not
-- enforce it — so `src/http-messenger/migrations.test.ts` scans this file for it.
--
-- This is also why this folder must be applied after `migrations/users`: the statement below
-- fails with `schema "saf_users" does not exist` otherwise, and registration order is
-- construction order.
CREATE TABLE "saf_http_messages"."messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"direction" text NOT NULL,
	"seq" integer NOT NULL,
	"text" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
	CONSTRAINT "messages_user_id_seq_unique" UNIQUE("user_id","seq"),
	CONSTRAINT "messages_direction_known" CHECK ("saf_http_messages"."messages"."direction" in ('inbound', 'outbound'))
);
--> statement-breakpoint
-- No `ON DELETE` behaviour is chosen because none is worth choosing: nothing removes a User
-- (ADR-0029), so this constraint never fires a cascade. It catches exactly one thing, an
-- agent copying an id wrong, and the route answers PostgreSQL's `23503` with a 404.
ALTER TABLE "saf_http_messages"."messages" ADD CONSTRAINT "messages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "saf_users"."users"("id") ON DELETE no action ON UPDATE no action;
