import type { MigrationDescriptor } from "../db/index.ts";
import { workerSchema } from "./schema.ts";

/**
 * The Signal Worker's migration descriptor: inert data registered with the Db,
 * which applies it alongside every other part's when `db.migrate()` is called and
 * verifies it at `db.start()` (ADR-0022, ADR-0032).
 *
 * The relative `../../migrations/signals` is what makes `dist` mirroring `src`
 * load-bearing — the same relative path has to reach the same folder from
 * `src/signals/migrations.ts` and from `dist/signals/migrations.js`. It is a `URL` and
 * not a path so that resolution is against this module rather than the working
 * directory: the folder ships inside the package, and a `process.cwd()` relative
 * path passes every test in this repository and breaks for every Operator.
 *
 * The SQL is generated by `npm run migrations:generate` and committed. Operators
 * never run a schema generation tool.
 */
export const signalsMigrations: MigrationDescriptor = {
  folder: new URL("../../migrations/signals", import.meta.url),
  // Taken from the schema object rather than spelled again: the tables are
  // compiled against that name, so a descriptor naming another would migrate one
  // place and read another, and every query would fail on a missing relation.
  schema: workerSchema.schemaName,
  table: "__migrations",
};
