import type { MigrationDescriptor } from "../db/index.ts";
import { usersSchema } from "./schema.ts";

/**
 * The User Directory's migration descriptor: inert data the Operator's entry point
 * hands to `db.migrate` alongside the Signal Worker's, in the one call they already make
 * (ADR-0021, ADR-0022).
 *
 * Its own schema and its own tracking table, and both are mandatory rather than
 * tidy: Drizzle's guard compares folder timestamps against only the newest row of a
 * tracker, so two parts sharing one would have the older part's migrations silently
 * skipped while `migrate` resolved successfully.
 *
 * The relative `../../migrations/users` is what makes `dist` mirroring `src`
 * load-bearing — the same relative path has to reach the same folder from
 * `src/users/migrations.ts` and from `dist/users/migrations.js`. It is a `URL` and
 * not a path so that resolution is against this module rather than the working
 * directory: the folder ships inside the package, and a `process.cwd()` relative
 * path passes every test in this repository and breaks for every Operator.
 *
 * The SQL is generated by `npm run migrations:generate -- --config
 * drizzle.users.config.ts` and committed. Operators never run a schema generation
 * tool.
 */
export const usersMigrations: MigrationDescriptor = {
  folder: new URL("../../migrations/users", import.meta.url),
  // Taken from the schema object rather than spelled again: the table is compiled
  // against that name, so a descriptor naming another would migrate one place and
  // read another, and every query would fail on a missing relation.
  schema: usersSchema.schemaName,
  table: "__migrations",
};
