import type { MigrationDescriptor } from "../db/index.ts";
import { coreSchema } from "./schema.ts";

/**
 * The Core's migration descriptor: inert data the Operator's entry point hands to
 * `db.migrate` alongside every other part's (ADR-0021, ADR-0022).
 *
 * The relative `../../migrations/core` is what makes `dist` mirroring `src`
 * load-bearing — the same relative path has to reach the same folder from
 * `src/core/migrations.ts` and from `dist/core/migrations.js`. It is a `URL` and
 * not a path so that resolution is against this module rather than the working
 * directory: the folder ships inside the package, and a `process.cwd()` relative
 * path passes every test in this repository and breaks for every Operator.
 *
 * The SQL is generated by `npm run migrations:generate` and committed. Operators
 * never run a schema generation tool.
 */
export const coreMigrations: MigrationDescriptor = {
  folder: new URL("../../migrations/core", import.meta.url),
  // Taken from the schema object rather than spelled again: the tables are
  // compiled against that name, so a descriptor naming another would migrate one
  // place and read another, and every query would fail on a missing relation.
  schema: coreSchema.schemaName,
  table: "__migrations",
};
