-- Generated by `npm run migrations:generate -- --config drizzle.scheduler.config.ts`,
-- then renamed and edited in one respect.
--
-- Renamed because `drizzle-kit` names a migration after two random words, and the `tag` in
-- `meta/_journal.json` was renamed with it: the journal is what names the file to read, so
-- the two must agree.
--
-- Edited to remove the `CREATE SCHEMA "saf_scheduler";` the generator wrote as its first
-- statement. `db.migrate` creates the descriptor's schema itself, because the tracking table
-- lives in it, so the generated line always arrives at a schema that already exists and fails
-- the very first migration of a new deployment. Every shipped folder has this line removed, and
-- `src/signals/migrations.test.ts` fails if one is left in, as does `src/scheduler/migrations.test.ts`
-- for this folder alone.
--
-- That is the **only** hand-edit here, unlike `migrations/http-messages`: a Schedule references
-- nobody, so there is no cross-schema foreign key for `drizzle-kit` to be unable to generate, and
-- this folder applies in any order relative to the others (ADR-0018).
--
-- `kind` carries `cron` in its check constraint though nothing writes it yet: the discriminant's
-- domain is fixed here so the cron arm is code and data rather than an `ALTER` of this constraint.
-- `schedules_once_has_at` refuses a `once` row with no instant, and is written so a `cron` row —
-- whose `at` is legitimately null — is unaffected.
CREATE TABLE "saf_scheduler"."schedules" (
	"name" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"at" timestamp with time zone,
	"data" jsonb,
	CONSTRAINT "schedules_kind_known" CHECK ("saf_scheduler"."schedules"."kind" in ('once', 'cron')),
	CONSTRAINT "schedules_once_has_at" CHECK ("saf_scheduler"."schedules"."kind" <> 'once' or "saf_scheduler"."schedules"."at" is not null)
);
