-- Generated by `npm run migrations:generate -- --config drizzle.decisions.config.ts`,
-- then renamed and edited in one respect.
--
-- Renamed because `drizzle-kit` names a migration after two random words, and the `tag` in
-- `meta/_journal.json` was renamed with it: the journal is what names the file to read, so
-- the two must agree.
--
-- Edited to remove the `CREATE SCHEMA "saf_decisions";` the generator wrote as its first
-- statement. `db.migrate` creates the descriptor's schema itself, because the tracking table
-- lives in it, so the generated line always arrives at a schema that already exists and fails
-- the very first migration of a new deployment. Every shipped folder has this line removed,
-- and `src/signals/migrations.test.ts` fails if one is left in.
--
-- That is the **only** hand-edit here, unlike `migrations/http-messages`: a Decision
-- references nobody, so there is no cross-schema foreign key for `drizzle-kit` to be unable to
-- generate, and this folder applies in any order relative to the others (ADR-0043).
--
-- `created_at` has no default on purpose, and it is the one line a reader may want to "fix" to
-- match `messages.created_at`. It must not: the timestamp is generated in JS and signed, so
-- the signed value and the stored value are one value, and a database default would make them
-- two.
CREATE TABLE "saf_decisions"."decisions" (
	"seq" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "saf_decisions"."decisions_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"statement" text NOT NULL,
	"jws" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
